// <auto-generated />
using System;
using AdminWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdminWeb.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260611224350_CleanupAdminStructureAndIndexes")]
    partial class CleanupAdminStructureAndIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("AdminWeb.Models.AdminActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TargetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetTable")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("admin_activity_logs", (string)null);
                });

            modelBuilder.Entity("AdminWeb.Models.Beacon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MacAddress")
                        .HasColumnType("TEXT");

                    b.Property<int>("Major")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Minor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlacementNote")
                        .HasColumnType("TEXT");

                    b.Property<int>("PoiId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Uuid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PoiId");

                    b.ToTable("beacons", (string)null);
                });

            modelBuilder.Entity("AdminWeb.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("IconUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("AdminWeb.Models.CategoryTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId", "LanguageCode")
                        .IsUnique();

                    b.ToTable("category_translations", (string)null);
                });

            modelBuilder.Entity("AdminWeb.Models.MediaAsset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PoiId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PoiId");

                    b.ToTable("media_assets", (string)null);
                });

            modelBuilder.Entity("AdminWeb.Models.MediaTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedLanguages")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastError")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int>("PoiId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProgressPercentage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("SucceededLanguages")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalLanguages")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PoiId");

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("media_tasks", null, t =>
                        {
                            t.HasCheckConstraint("CK_media_tasks_progress_percentage", "\"ProgressPercentage\" >= 0 AND \"ProgressPercentage\" <= 100");
                        });
                });

            modelBuilder.Entity("AdminWeb.Models.Poi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdminNote")
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CreatorId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(10,8)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(11,8)");

                    b.Property<string>("QrCodeToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Radius")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.ToTable("pois", (string)null);
                });

            modelBuilder.Entity("AdminWeb.Models.PoiCategory", b =>
                {
                    b.Property<int>("PoiId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PoiId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("poi_categories", (string)null);
                });

            modelBuilder.Entity("AdminWeb.Models.PoiTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AudioDuration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AudioUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("PoiId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShortDescription")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("TtsScript")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PoiId", "LanguageCode")
                        .IsUnique();

                    b.ToTable("poi_translations", (string)null);
                });

            modelBuilder.Entity("AdminWeb.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TouristId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TouristId");

                    b.ToTable("reviews", (string)null);
                });

            modelBuilder.Entity("AdminWeb.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("AdminWeb.Models.SupportedLanguage", b =>
                {
                    b.Property<string>("LanguageCode")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("EdgeTtsVoice")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LanguageName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("LanguageCode");

                    b.ToTable("supported_languages", (string)null);

                    b.HasData(
                        new
                        {
                            LanguageCode = "en",
                            EdgeTtsVoice = "en-US-AriaNeural",
                            IsActive = true,
                            LanguageName = "English"
                        },
                        new
                        {
                            LanguageCode = "ja",
                            EdgeTtsVoice = "ja-JP-NanamiNeural",
                            IsActive = true,
                            LanguageName = "Japanese"
                        },
                        new
                        {
                            LanguageCode = "ko",
                            EdgeTtsVoice = "ko-KR-SunHiNeural",
                            IsActive = true,
                            LanguageName = "Korean"
                        });
                });

            modelBuilder.Entity("AdminWeb.Models.SyncVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("VersionNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("VersionNumber")
                        .IsUnique();

                    b.ToTable("sync_versions", (string)null);
                });

            modelBuilder.Entity("AdminWeb.Models.SystemSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("SettingKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SettingValue")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SettingKey")
                        .IsUnique();

                    b.ToTable("system_settings", (string)null);
                });

            modelBuilder.Entity("AdminWeb.Models.Tour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("EstimatedTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("tours", (string)null);
                });

            modelBuilder.Entity("AdminWeb.Models.TourPoi", b =>
                {
                    b.Property<int>("TourId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PoiId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SequenceOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("TourId", "PoiId");

                    b.HasIndex("PoiId");

                    b.ToTable("tour_pois", (string)null);
                });

            modelBuilder.Entity("AdminWeb.Models.TourTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TourId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TourId", "LanguageCode")
                        .IsUnique();

                    b.ToTable("tour_translations", (string)null);
                });

            modelBuilder.Entity("AdminWeb.Models.Tourist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthProvider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("tourists", (string)null);
                });

            modelBuilder.Entity("AdminWeb.Models.TouristFavorite", b =>
                {
                    b.Property<int>("TouristId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetType")
                        .HasColumnType("TEXT");

                    b.Property<int>("TargetId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("TouristId", "TargetType", "TargetId");

                    b.ToTable("tourist_favorites", (string)null);
                });

            modelBuilder.Entity("AdminWeb.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("AdminWeb.Models.VisitorPlaybackLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ListenDuration")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PoiId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TouristId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("VisitorLatitude")
                        .HasColumnType("decimal(10,8)");

                    b.Property<decimal?>("VisitorLongitude")
                        .HasColumnType("decimal(11,8)");

                    b.HasKey("Id");

                    b.HasIndex("PoiId");

                    b.HasIndex("TouristId");

                    b.ToTable("visitor_playback_logs", (string)null);
                });

            modelBuilder.Entity("AdminWeb.Models.AdminActivityLog", b =>
                {
                    b.HasOne("AdminWeb.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AdminWeb.Models.Beacon", b =>
                {
                    b.HasOne("AdminWeb.Models.Poi", "Poi")
                        .WithMany("Beacons")
                        .HasForeignKey("PoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Poi");
                });

            modelBuilder.Entity("AdminWeb.Models.CategoryTranslation", b =>
                {
                    b.HasOne("AdminWeb.Models.Category", "Category")
                        .WithMany("Translations")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("AdminWeb.Models.MediaAsset", b =>
                {
                    b.HasOne("AdminWeb.Models.Poi", "Poi")
                        .WithMany("MediaAssets")
                        .HasForeignKey("PoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Poi");
                });

            modelBuilder.Entity("AdminWeb.Models.MediaTask", b =>
                {
                    b.HasOne("AdminWeb.Models.Poi", "Poi")
                        .WithMany("MediaTasks")
                        .HasForeignKey("PoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Poi");
                });

            modelBuilder.Entity("AdminWeb.Models.Poi", b =>
                {
                    b.HasOne("AdminWeb.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("AdminWeb.Models.PoiCategory", b =>
                {
                    b.HasOne("AdminWeb.Models.Category", "Category")
                        .WithMany("PoiCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdminWeb.Models.Poi", "Poi")
                        .WithMany("PoiCategories")
                        .HasForeignKey("PoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Poi");
                });

            modelBuilder.Entity("AdminWeb.Models.PoiTranslation", b =>
                {
                    b.HasOne("AdminWeb.Models.Poi", "Poi")
                        .WithMany("Translations")
                        .HasForeignKey("PoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Poi");
                });

            modelBuilder.Entity("AdminWeb.Models.Review", b =>
                {
                    b.HasOne("AdminWeb.Models.Tourist", "Tourist")
                        .WithMany("Reviews")
                        .HasForeignKey("TouristId");

                    b.Navigation("Tourist");
                });

            modelBuilder.Entity("AdminWeb.Models.TourPoi", b =>
                {
                    b.HasOne("AdminWeb.Models.Poi", "Poi")
                        .WithMany("TourPois")
                        .HasForeignKey("PoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdminWeb.Models.Tour", "Tour")
                        .WithMany("TourPois")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Poi");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("AdminWeb.Models.TourTranslation", b =>
                {
                    b.HasOne("AdminWeb.Models.Tour", "Tour")
                        .WithMany("Translations")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("AdminWeb.Models.TouristFavorite", b =>
                {
                    b.HasOne("AdminWeb.Models.Tourist", "Tourist")
                        .WithMany("Favorites")
                        .HasForeignKey("TouristId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tourist");
                });

            modelBuilder.Entity("AdminWeb.Models.User", b =>
                {
                    b.HasOne("AdminWeb.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("AdminWeb.Models.VisitorPlaybackLog", b =>
                {
                    b.HasOne("AdminWeb.Models.Poi", "Poi")
                        .WithMany("PlaybackLogs")
                        .HasForeignKey("PoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdminWeb.Models.Tourist", "Tourist")
                        .WithMany("PlaybackLogs")
                        .HasForeignKey("TouristId");

                    b.Navigation("Poi");

                    b.Navigation("Tourist");
                });

            modelBuilder.Entity("AdminWeb.Models.Category", b =>
                {
                    b.Navigation("PoiCategories");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("AdminWeb.Models.Poi", b =>
                {
                    b.Navigation("Beacons");

                    b.Navigation("MediaAssets");

                    b.Navigation("MediaTasks");

                    b.Navigation("PlaybackLogs");

                    b.Navigation("PoiCategories");

                    b.Navigation("TourPois");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("AdminWeb.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("AdminWeb.Models.Tour", b =>
                {
                    b.Navigation("TourPois");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("AdminWeb.Models.Tourist", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("PlaybackLogs");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
